
# Time Shall Not Pass General Config
[TimeShallNotPass]
	# Determines whether players added to the exclusion list can connect to the server without causing any Time Shall Not Pass modules to toggle off. Default: [false]
	allowPlayerExclusions = false
	# Tells Time Shall Not Pass if extra logging should be done in the server console and log file. This will give you a break-down of what each module is doing. Default: [false]
	verboseLogging = false
	# The players that can connect to the server without causing any Time Shall Not Pass modules to toggle off. Example: ["playerName: playerUUID"]
	excludedPlayers = []

# Time Shall Not Pass Modules Config
[TimeShallNotPassModules]
	# Controls if Time Shall Not Pass will disable the daylight cycle when there are no non-excluded players connected. Default: [true]
	daylightCycleModule = false
	# Controls if Time Shall Not Pass will disable random ticks when there are no non-excluded players connected. Default: [false]
	randomTicksModule = false
	# Controls if Time Shall Not Pass will disable tile entity ticks when there are no non-excluded players connected. Default: [false]
	tileEntityTicksModule = false
	# Controls if Time Shall Not Pass will disable fire ticks when there are no non-excluded players connected. Default: [false]
	fireTicksModule = false
	# Controls if Time Shall Not Pass will disable the weather cycle when there are no non-excluded players connected. Default: [false]
	weatherCycleModule = false

